project:
  type: website

website:
  title: "Matan Hakim - Policy Data Scientist"
  navbar:
    right:
      - index.qmd
      - cv.qmd
      - icon: github
        href: https://github.com/matanhakim
      - icon: twitter
        href: https://twitter.com/MatanHakim
      - icon: mastodon
        href: https://fosstodon.org/@matanhakim
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

