project:
  type: website

website:
  title: "Matan Hakim - Policy Data Scientist"
  site-url: https://www.matanhakim.org
  description: "Matan Hakim's personal website"
  navbar:
    right:
      - text: "About"
        file: index.qmd
      - text: "Blog"
        file: posts.qmd
      - text: "CV"
        file: cv.qmd
      - icon: github
        href: https://github.com/matanhakim
      - icon: twitter
        href: https://twitter.com/MatanHakim
      - icon: mastodon
        href: https://fosstodon.org/@matanhakim
        rel: me
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual
